apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    app: Vote-App
    type: frontend
spec:
  template:
    metadata:
      name: Vote-Pod
      labels:
        app: Vote-App
        type: frontend
    spec:
      containers:
        - name: vote
          image: 000h/vote
          ports:
          - containerPort: 80
